version: '3.7'
services:
  db:
    image: postgres
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - '5432:5432'
