version: 2.1
jobs:
  test:
    docker:
      - image: cimg/node:20.14.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test

workflows:
  version: 2
  test:
    jobs:
      - test