import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import { AuthProvider } from "./components/AuthProvider";
import Header from "./components/Header";
import PageAnimatePresence from "./components/HOC/PageAnimatePresence";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const plusjakartasans = Plus_Jakarta_Sans({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Minecraft Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + ' bg-black'}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
