import { Toaster } from '@/components/ui/toaster';
import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import { Inter } from 'next/font/google';
import NextAuthProvider from './contexts/NextAuthProvider';
import ReactIntlProvider from './contexts/ReactIntlProvider';
import { ReduxProvider } from './contexts/ReduxProvider';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Minecraft Clone',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ReactIntlProvider>
          <ThemeProvider attribute='class' defaultTheme='light' enableSystem>
            <NextAuthProvider>
              <ReduxProvider>{children}</ReduxProvider>
            </NextAuthProvider>
          </ThemeProvider>
        </ReactIntlProvider>
        <Toaster />
      </body>
    </html>
  );
}
